import type { Metadata } from "next";
import "@/styles/globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { ThemeChangeButton } from "@/components/theme/theme-change-btn";
import { AppSidebar } from "@/components/navigation/app-sidebar";
import { Separator } from "@/components/ui/separator";
import { Toaster } from "@/components/ui/toaster";

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="cs" suppressHydrationWarning>
         <body>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
               <SidebarProvider>
                  <AppSidebar />
                  <SidebarInset>
                     <header className="flex h-16 shrink-0 items-center gap-2">
                        <div className="flex items-center gap-2 px-4">
                           <SidebarTrigger className="-ml-1" />
                           <Separator orientation="vertical" className="mr-2 h-4" />
                           <ThemeChangeButton />
                        </div>
                     </header>
                     <main className="flex flex-1 flex-col gap-4 p-4 pt-0">{children}</main>
                  </SidebarInset>
               </SidebarProvider>
               <Toaster />
            </ThemeProvider>
            <Toaster />
         </body>
      </html>
   );
}
