name: Code Scan CI
run-name: ${{ github.actor }} is testing out Code Scan 🚀
on:
  pull_request:
    branches:
      - 'feature/*'
jobs:
  Code-Scan-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Test the code
        run: npm run lint
