name: Dependabot CI
on:
  pull_request:
    branches:
      - 'dependabot/*'
jobs:
  Dependabot-CI:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: Run the application
        run: npm run start
