name: Dependabot CI
on:
  pull_request:
    branches:
      - main
    tags:
      - deps-update
jobs:
  Dependabot-CI:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: Run the application
        run: npm run start
